require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - bin/*
    - vendor/**/*
    - db/schema.rb

Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 99

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Bundler/OrderedGems:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*

Style/SymbolArray:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - db/migrate/*