default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] || 'sd_logbook' %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['DB_TEST_NAME'] || 'sd_logbook_test' %>

production:
  <<: *default
