name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby 3.1.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-ruby-${{ hashFiles('./Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-ruby-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run Rubocop
        run: bundle exec rubocop --parallel

  deploy_to_heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs:
      - rubocop
    if: ${{ github.ref_name == 'master' && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: sd-dubai
          heroku_email: konfeta333@gmail.com
